In [2]:
#this is hello world print code.
print("Hello, World!")

Hello, World!


In [3]:
#python indentation.
if 5 > 2:
  print("Five is greater than two!")

Five is greater than two!


In [4]:
#python indentation.
if 5 > 2:
print("Five is greater than two!")

IndentationError: ignored

In [18]:
"""
This is a comment
written in
more than just one line
"""
print("Hello, World!")

Hello, World!


In [19]:
#variables in python.
x=5
y="Hello"

print(x)
print(y)

5
Hello


In [20]:
x=4 #x is int type
x="Hello" #x is now str type
print(x)

Hello


In [21]:
#specify datatype with casting.
x = str(3)
y = int(3)
z = float(3)
print(x)
print(y)
print(z)

3
3
3.0


In [22]:
#find datatype
x = 5
y = "John"
print(type(x))
print(type(y))

<class 'int'>
<class 'str'>


In [23]:
#single and double quotes are same.
x = "Sally"
print(x)
y = 'John'
print(y)

Sally
John


In [24]:
#case sensitive.
a = 4
A = "Sally"
#A will not overwrite a
print(a)

4


In [25]:
#multiple variable in one line.
x,y,z="Orange","Banana","Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry


In [26]:
#same value to multiple variables
x=y=z="Orange"
print(x)
print(y)
print(z)

Orange
Orange
Orange


In [27]:
#unpack a list.
fruits = ["apple","banana","cherry"]
x, y, z = fruits
print(x)
print(y)
print(z)

apple
banana
cherry


In [28]:
#output variables.
x = "Python is awesome"
print(x)

Python is awesome


In [29]:
x = "Python"
y = "is"
z = "awesome"
print(x, y, z)

Python is awesome


In [30]:
x = "Python "
y = "is "
z = "awesome"
print(x + y + z)

Python is awesome


In [31]:
x = 5
y = 10
print(x+y)

15


In [32]:
"""In the print() function, when you try to combine a string
and a number with the + operator, Python will give you an error
"""
x = 5
y = "John"
print(x+y)

TypeError: ignored

In [33]:
x = 5
y = "John"
print(x,y)

5 John


In [34]:
#global & local variable
x = "awesome"

def myfunc():
  x = "fantastic"
  print("Python is " + x)

myfunc()
print("Python is " + x)

Python is fantastic
Python is awesome


In [35]:
#global keyword
def myfunc():
  global x
  x = "fantastic"
myfunc()
print("Python is " + x)

Python is fantastic


In [36]:
x = "awesome"
def myfunc():
  global x
  x = "fantastic"
  print("Python is " + x)
myfunc()
print("Python is " + x)

Python is fantastic
Python is fantastic


In [37]:
#convert from one type to another
x = 1 #int
y = 2.5 #float
z = 1j #complex

#convert from int to float:
a = float(x)

#convert from float to int:
b = int(y)

#convert from int to complex:
c = complex(x)

print(a)
print(b)
print(c)

print(type(a))
print(type(b))
print(type(c))

1.0
2
(1+0j)
<class 'float'>
<class 'int'>
<class 'complex'>


In [38]:
#specify a variable type
x = 1
y = 2.2
z = "3"
print(int(x))
print(int(y))
print(int(z))

print(float(x))
print(float(y))
print(float(z))

x = "s1"
print(str(x))
print(str(y))
print(str(z))



1
2
3
1.0
2.2
3.0
s1
2.2
3


In [39]:
a = "Hello"
print(a[1])

e


In [40]:
#loop through a string
for x in "banana":
  print(x)

b
a
n
a
n
a


In [41]:
#string length
x = "banana"
print(len(x))

6


In [42]:
#check string
txt = "The best things in life are free"
print("life" in txt)
print("cost" in txt)

True
False


In [43]:
txt = "The best things in life are free"
if "free" in txt:
  print("Yes, 'free' is present.")
else:
  print("No, 'free' is not present")

Yes, 'free' is present.


In [44]:
txt = "The best things in life are free"
if "cost" in txt:
  print("Yes, 'cost' is present.")
else:
  print("No, 'cost' is not present")

No, 'cost' is not present


In [45]:
#string slicing
a = "Hello World"
print(a[2:5])
print(a[:5])
print(a[2:])
print(a[-5:-2])

llo
Hello
llo World
Wor


In [46]:
#upper case
a = "Hello, World!"
print(a.upper())

HELLO, WORLD!


In [47]:
#lower case
a = "HELLO, WORLD"
print(a.lower())

hello, world


In [48]:
#remove whitespace
a = " Hello, World! "
print(a.strip())

Hello, World!


In [49]:
#replace
a = "Jello, World"
print(a)
print(a.replace("J","H"))

Jello, World
Hello, World


In [50]:
#split string
a = "Hello, World"
b = a.split(",")
print(b)

['Hello', ' World']


In [51]:
#string concatenation
a = "Hello"
b = "World"
c = a + b
print(c)
c = a + " " + b
print(c)

HelloWorld
Hello World


In [52]:
#string format
age = 24
txt = "My name Sajib, I am " + age
print(txt)

TypeError: ignored

In [53]:
#use format() function
age = 24
txt = "My name is Sajib, I am {}"
print(txt.format(age))

My name is Sajib, I am 24


In [54]:
#format() method takes unlimited number of arguments
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity,itemno,price))

I want 3 pieces of item 567 for 49.95 dollars.


In [55]:
#format() with index numbers
quantity = 3
itemno = 567
price = 49.95
myorder = "I want to pay {2} dollars for {0} pieces of item {1}."
print(myorder.format(quantity,itemno,price))

I want to pay 49.95 dollars for 3 pieces of item 567.


In [56]:
#list
list1 = ["apple","banana","cherry"]
print(list1)
list1[1] = "mango"
print(list1)

['apple', 'banana', 'cherry']
['apple', 'mango', 'cherry']


In [57]:
#append items
list1 = ["apple","banana","cherry"]
list1.append("orange")
print(list1)

['apple', 'banana', 'cherry', 'orange']


In [58]:
#insert
list1 = ["apple","banana","cherry"]
list1.insert(1,"orange")
print(list1)

['apple', 'orange', 'banana', 'cherry']


In [59]:
#extend list
list1 = ["apple","banana","cherry"]
list2 = ["orange","mango","papaya"]
list1.extend(list2)
print(list1)

['apple', 'banana', 'cherry', 'orange', 'mango', 'papaya']


In [60]:
#add tuple
list1 = ["apple","banana","cherry"]
tuple = ("orange","mango")
list1.extend(tuple)
print(list1)

['apple', 'banana', 'cherry', 'orange', 'mango']


In [61]:
#remove item
list1 = ["apple","banana","cherry"]
list1.remove("banana")
print(list1)

['apple', 'cherry']


In [62]:
#remove specified index
list1 = ["apple","banana","cherry"]
list1.pop(1)
print(list1)

['apple', 'cherry']


In [63]:
#delete entire list
list1 = ["apple","banana","cherry"]
del list1

In [64]:
#clear the list contents
list1 = ["apple","banana","cherry"]
list1.clear()
print(list1)

[]


In [65]:
#Sort the list alphabetically:
#ascending
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort()
print(thislist)

['banana', 'kiwi', 'mango', 'orange', 'pineapple']


In [66]:
#Sort the list numerically:
list1 = [100, 50, 65, 82, 23]
list1.sort()
print(list1)

[23, 50, 65, 82, 100]


In [67]:
#descending
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.sort(reverse=True)
print(thislist)

['pineapple', 'orange', 'mango', 'kiwi', 'banana']


In [68]:
list1 = [100, 50, 65, 82, 23]
list1.sort(reverse=True)
print(list1)

[100, 82, 65, 50, 23]


In [69]:
#reverse
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
thislist.reverse()
print(thislist)

['banana', 'pineapple', 'kiwi', 'mango', 'orange']


In [70]:
#copy
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
mylist=thislist.copy()
print(mylist)

['orange', 'mango', 'kiwi', 'pineapple', 'banana']


In [71]:
#Make a copy of a list with the list() method:
thislist = ["orange", "mango", "kiwi", "pineapple", "banana"]
mylist=list(thislist)
print(mylist)

['orange', 'mango', 'kiwi', 'pineapple', 'banana']


In [72]:
#tuple
thistuple = ("apple", "banana", "cherry")
print(thistuple)

('apple', 'banana', 'cherry')


In [73]:
#set
thisset = {"apple", "banana", "cherry"}
print(thisset)

{'apple', 'banana', 'cherry'}


In [74]:
#dictionary
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "year": 2020
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 2020}


In [75]:
#adding items
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
thisdict["color"] = "red"
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'red'}


In [76]:
#Nested Dictionaries
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}
print(myfamily)

{'child1': {'name': 'Emil', 'year': 2004}, 'child2': {'name': 'Tobias', 'year': 2007}, 'child3': {'name': 'Linus', 'year': 2011}}


In [77]:
import numpy as np
print(np.__version__)

1.22.4


In [78]:
arr = np.array([1,2,3,4])
print(arr)
print(type(arr))
print(arr.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [79]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array(['apple', 'banana', 'cherry'])

print(arr1.dtype)
print(arr2.dtype)

int64
<U6


In [80]:
#2-D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [81]:
#3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [82]:
#higher dimesions
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [83]:
#array indexing
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [84]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [85]:
#access 2-D array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [86]:
#access 3-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [87]:
#negative indexing
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [90]:
#array slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [91]:
#negative slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])
print(arr[-3:])
print(arr[:-3])


[5 6]
[5 6 7]
[1 2 3 4]


In [92]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::1])
print(arr[::2])
print(arr[::3])
print(arr[::4])

[1 2 3 4 5 6 7]
[1 3 5 7]
[1 4 7]
[1 5]


In [93]:
#Slicing 2-D Arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [97]:
#converting datatype
arr1 = np.array([1.1, 2.1, 3.1])
arr2 = np.array([1, 2, 3])
arr3 = np.array([1, 0, 3])

newarr1 = arr1.astype('i')
newarr2 = arr2.astype('f')
newarr3 = arr3.astype(bool)

print(newarr1)
print(newarr1.dtype)

print(newarr2)
print(newarr2.dtype)

print(newarr3)
print(newarr3.dtype)

[1 2 3]
int32
[1. 2. 3.]
float32
[ True False  True]
bool


In [98]:
#copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [99]:
#view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [100]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [101]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [102]:
#shape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [103]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [104]:
#reshape
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [105]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [106]:
#unknown dimesion
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [107]:
#flattening the arrays
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [110]:
#iterating
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [111]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [112]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [113]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [114]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [115]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


In [116]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [117]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [118]:
#Join
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [119]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [120]:
#stack function
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [121]:
#stack along rows
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [122]:
#stack along coloumn
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [123]:
#stack along height
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [124]:
#splitting
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [125]:
#array search
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [126]:
#sort
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [127]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [128]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [129]:
#filter array
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
